config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "boards#index"

  resources :boards do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end 
  end

  resource :profile, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true

    belongs_to :user
    has_many :tasks, dependent: :destroy

    def display_created_at
        I18n.l(self.created_at, format: :default)
    end

    def author_name
        user.display_name
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :task
end

app/models/profile.rb
class Profile < ApplicationRecord
    enum gender: { male: 0, female: 1, other: 2 }
    belongs_to :user
    has_one_attached :avatar

    def age
        return '不明' unless birthday.present?
        years = Time.zone.now.year - birthday.year
        days = Time.zone.now.yday - birthday.yday

        if days < 0
            "#{years -1}歳"
        else
            "#{years}歳"
        end
    end
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    belongs_to :board

    has_many :comments, dependent: :destroy

    has_one_attached :eyecatch

    def display_created_at
        I18n.l(self.created_at, format: :default)
    end

    def author_name
        user.display_name
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  has_one :profile, dependent: :destroy

  delegate :birthday, :age, :gender, to: :profile, allow_nil: true

  def display_name
    profile&.nickname || self.email.split('@').first
  end

  def avatar_image
    if profile&.avatar&.attached?
      profile.avatar
    else
      'default-avatar.png'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
    before_action :set_board, only: [:show]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    def index
        @boards = Board.all
    end

    def show
        @tasks = @board.tasks
    end

    def new
        @board = current_user.boards.build
    end

    def create
        @board = current_user.boards.build(board_params)
        if @board.save
            redirect_to board_path(@board), notice: '保存できました'
        else
            flash.now[:error] = '保存に失敗しました'
            render :new
        end
    end

    def edit
        @board = current_user.boards.find(params[:id])
    end

    def update
        @board = current_user.boards.find(params[:id])
        if @board.update(board_params)
            redirect_to board_path(@board), notice: '更新できました'
        else
            flash.now[:error] = '更新に失敗しました'
            render :edit
        end
    end

    def destroy
        board = current_user.boards.find(params[:id])
        board.destroy!
        redirect_to root_path, notice: '削除に成功しました'
    end

    private
    def board_params
        params.require(:board).permit(:title, :content)
    end

    def set_board
        @board = Board.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        task = Task.find(params[:task_id])
        @comment = task.comments.build
    end

    def create
        task = Task.find(params[:task_id])
        @comment = task.comments.build(comment_params)
        @comment.user = current_user
        if @comment.save
            redirect_to board_task_path(task.board, task.id), notice: 'Comment Add'
        else
            flash.now[:error] = 'Update Failed'
            render :new
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!

    def show
        @profile = current_user.profile
        @user = current_user
    end

    def edit
        if current_user.profile.present?
            @profile = current_user.profile
        else
            @profile = current_user.build_profile
        end
    end

    def update
        @profile = current_user.profile || current_user.build_profile
        @profile.assign_attributes(profile_params)
        if @profile.save
            redirect_to profile_path, notice: 'プロフィールを更新'
        else
            flash.now[:error] = '更新できませんでした'
            render :edit
        end
    end

    private
    def profile_params
        params.require(:profile).permit(
            :nickname,
            :introduction,
            :gender,
            :birthday,
            :subscribe,
            :avatar
        )
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show]
    before_action :authenticate_user!

    def show
        @comments = @task.comments
    end

    def new
        board = Board.find(params[:board_id])
        @task = board.tasks.build
    end

    def create
        board = Board.find(params[:board_id])
        @task = board.tasks.build(task_params)
        @task.user = current_user
        if @task.save
            redirect_to board_path(board), notice: 'add Task'
        else
            flash.now[:error] = '更新できませんでした'
            render :new
        end
    end

    def edit
        @task = current_user.tasks.find(params[:id])
    end

    def update
        @task = current_user.tasks.find(params[:id])
        if @task.update(task_params)
            redirect_to board_path(@task.board), notice: 'Update Successful'
        else
            flash.now[:error] = 'Update Failed'
            render :edit
        end
    end

    def destroy
        task = current_user.tasks.find(params[:id])
        task.destroy!
        redirect_to board_path(task.board), notice: 'Destroy Successful'
    end

    private
    def task_params
        params.require(:task).permit(
            :title,
            :content,
            :deadline,
            :eyecatch
        )
    end

    def set_task
        @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.erb
<%= link_to board_path(board) do %>
    <div class="card">
        <div class="card_content">
            <div class="card_title"><%= board.title %></div>
            <div class="card_description"><%= board.content %></div>
            <div class="card_detail">
                <%= image_tag board.user.avatar_image %>
                <div>
                    <p><%= board.author_name %></p>
                    <p><%= board.display_created_at %></p>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/boards/_form.html.erb
<div class="container">
    <ul>
        <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <%= form_with model: board, local: true do |f| %>
        <div>
            <%= f.label :title, 'Name' %>
        </div>
        <div>
            <%= f.text_field :title %>
        </div>
        <div>
            <%= f.label :content, 'Description' %>
        </div>
        <div>
            <%= f.text_area :content, class: 'text' %>
        </div>
        <div>
            <%= f.submit 'Submit', class: 'btn-primary' %>
        </div>
    <% end %>
</div>

app/views/boards/_task.html.erb
<%= link_to board_task_path(task.board, task) do %>
    <div class="card">
        <% if task.eyecatch.attached? %>
            <div class="card_image">
                <%= image_tag task.eyecatch %>
            </div>
        <% end %>
        <div class="card_content">
            <div class="card_title"><%= task.title %></div>
            <div class="card_detail">
                <%= image_tag task.user.avatar_image %>
                <div>
                    <p><%= task.author_name %></p>
                    <p><%= task.display_created_at %></p>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/boards/edit.html.erb
<%= render 'form', board: @board %>

app/views/boards/index.html.erb
<div class="container">
    <h2>Brackets</h2>
    <% @boards.each do |board| %>
        <%= render board, board: board %>
    <% end %>
    <%= link_to new_board_path do %>
        <div class="card card_new_board float_btn2" >+ Add new board</div>
    <% end %>
</div>

app/views/boards/new.html.erb
<h2>New Board</h2>
<%= render 'form', board: @board %>

app/views/boards/show.html.erb
<div class="board">
    <h1 class="board_title"><%= @board.title %></h1>
    <div class="board_detail">
        <%= image_tag @board.user.avatar_image %>
        <% if user_signed_in? && current_user.boards.exists?(@board.id) %>
            <div class="board_detail_action">
                <div class="dropdown">
                    <%= image_tag "actions.svg", class: 'dropbtn' %>
                    <div class="dropdown-content mini">
                        <%= link_to 'Edit', edit_board_path(@board) %>
                        <%= link_to 'Delete', board_path(@board), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' } %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="board_content">
        <%= @board.content %>
    </div>
</div>

<h2>Tasks</h2>
<% @tasks.each do |task| %>
    <div class="board">
        <%= render 'task', task: task %>
    </div>
<%end%>

<div class="container">
    <%= link_to new_board_task_path(@board) do %>
        <div class="card card_new_board" >+ Add new task</div>
    <% end %>
</div>

app/views/comments/new.html.erb
New Comment
<div class="container">
    <ul>
        <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <%= form_with(model: @comment, url: board_task_comments_path(@comment.task), local: true) do |f| %>
        <div>
            <%= f.label :content, 'Commment' %>
        </div>
        <div>
            <%= f.text_area :content, class: 'text' %>
        </div>
        <div>
            <%= f.submit 'Submit', class: 'btn-primary' %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TTodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <header class="header" >
      <div class="header_logos">
        <% if !current_page?(root_path) %>
          <%= link_to :back do %>
            <%= image_tag 'back.svg', class: 'header_back' %>
          <% end %>
        <% end %>
        <%= link_to root_path do %>
          <p class="header_pageTitle">Boards</p>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <div class="dropdown">
          <%= image_tag current_user.avatar_image, class: 'header_avatar dropbtn' %>
          <div class="dropdown-content">
            <%= link_to 'プロフィール', profile_path %>
            <%= link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete'} %>
          </div>
        </div> 
      <% else %>
        <%= link_to 'ユーザ登録', new_user_registration_path, class: 'header_loginBtn' %>
        <%= link_to 'ログイン', user_session_path, data: { method: 'post'}, class: 'header_loginBtn' %>
      <% end %>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/profiles/edit.html.erb
Profile Edit
<div class="container">
    <ul>
        <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <%= form_with(model: @profile, url: profile_path, method: 'put', local: true) do |f| %>
        <div>
            <%= f.label :avatar, 'avatar' %>
        </div>
        <div>
            <%= f.file_field :avatar %>
        </div>
        <div>
            <%= f.label :nickname, 'nickname' %>
        </div>
        <div>
            <%= f.text_field :nickname, class: 'text' %>
        </div>
        <div>
            <%= f.label :introduction, 'introduction' %>
        </div>
        <div>
            <%= f.text_area :introduction, class: 'text' %>
        </div>
        <div>
            <%= f.label :gender, 'gender' %>
        </div>
        <div>
            <%= f.select :gender, Profile.genders.keys, {}, { class: 'text' } %>
        </div>
        <div>
            <%= f.label :birthday, 'birthday' %>
        </div>
        <div>
            <%= f.date_field :birthday, class: 'text' %>
        </div>
        <div>
            <%= f.label :subscribe, 'subscribe' %>
            <%= f.check_box :subscribe %>
        </div>
        <div>
            <%= f.submit 'Submit', class: 'btn-primary' %>
        </div>
    <% end %>
</div>

app/views/profiles/show.html.erb
<div class="container profilePage">
    <div class="profilePage_user">
        <div class="profilePage_user_image">
            <%= image_tag @user.avatar_image %>
        </div>
        <div class="profilePage_user_basicInfo">
            <div class="profilePage_user_name">
                <div class="profilePage_user_displayName">
                <%= @user.display_name %>
                (<%= (@user.age || '？歳') %>
                ・
                <%= I18n.t("enum.genders.#{@user.gender || 'unknown'}") %>)
                </div>
                <div class="profilePage_user_actionButton">
                    <% if @user == current_user %>
                        <%= link_to 'Edit', edit_profile_path %>
                    <% end %>
                </div>
            </div>
            <div class="profilePage_user_introduction">
                <%= @user.profile&.introduction %>
            </div>
        </div>
    </div>
</div>

app/views/tasks/edit.html.erb
Tasks Edit
<div class="container">
    <ul>
        <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <%= form_with(model: @task, url: board_task_path(@task.board, @task), local: true) do |f| %>
        <div>
            <%= f.label :eyecatch, 'eyecatch' %>
        </div>
        <div>
            <%= f.file_field :eyecatch %>
        </div>
        <div>
            <%= f.label :title, 'Name' %>
        </div>
        <div>
            <%= f.text_field :title, class: 'text' %>
        </div>
        <div>
            <%= f.label :content, 'Description' %>
        </div>
        <div>
            <%= f.text_area :content, class: 'text' %>
        </div>
        <div>
            <%= f.label :deadline, 'Deadline' %>
        </div>
        <div>
            <%= f.datetime_field :deadline %>
        </div>
        <div>
            <%= f.submit 'Submit', class: 'btn-primary' %>
        </div>
    <% end %>
</div>

app/views/tasks/new.html.erb
Tasks New
<div class="container">
    <ul>
        <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <%= form_with(model: @task, url: board_tasks_path(@task.board), local: true) do |f| %>
        <div>
            <%= f.label :eyecatch, 'eyecatch' %>
        </div>
        <div>
            <%= f.file_field :eyecatch %>
        </div>
        <div>
            <%= f.label :title, 'Name' %>
        </div>
        <div>
            <%= f.text_field :title, class: 'text' %>
        </div>
        <div>
            <%= f.label :content, 'Description' %>
        </div>
        <div>
            <%= f.text_area :content, class: 'text' %>
        </div>
        <div>
            <%= f.label :deadline, 'Deadline' %>
        </div>
        <div>
            <%= f.datetime_field :deadline %>
        </div>
        <div>
            <%= f.submit 'Submit', class: 'btn-primary' %>
        </div>
    <% end %>
</div>

app/views/tasks/show.html.erb
Task Show
<div class="board">
    <% if @task.eyecatch.attached? %>
        <div class="card_image">
            <%= image_tag @task.eyecatch %>
        </div>
    <% end %>
    <h1 class="board_title"><%= @task.title %></h1>
    <div class="board_detail">
        <%= image_tag @task.user.avatar_image %>
        <% if user_signed_in? && current_user.tasks.exists?(@task.id) %>
            <div class="board_detail_action">
                <div class="dropdown">
                    <%= image_tag "actions.svg", class: 'dropbtn' %>
                    <div class="dropdown-content mini">
                        <%= link_to 'Edit', edit_board_task_path(@task) %>
                        <%= link_to 'Delete', board_task_path(@task), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' } %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <div class="board_content">
        <%= @task.content %>
    </div>
</div>

<div class="board">
    <h2>Comments</h2>
    <% @comments.each do |comment| %>
        <div class="board_comment">
            <div class="board_detail">
                <% if comment.user.avatar_image.attached? %>
                    <%= image_tag comment.user.avatar_image, class: 'comment-img' %>
                <% else %>
                    <%= image_tag 'default-avatar.png' %>
                <% end %>
                <p><%= comment.content %></p>
            </div>
        </div>
    <% end %>
</div>

<div class="container">
    <%= link_to new_board_task_comment_path(@task.board_id, @task.id) do %>
        <div class="card card_new_board" >+ Add new Comment</div>
    <% end %>
</div>